phases:
  - phase: foundation_deployment
    displayName: build Azure function foundation
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    queue:
      name: Hosted VS2017
      demands: DotNetFramework
      matrix:
        functionapp:
          templateName: functionapp
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: Deploy resource group template
      inputs:
        action: 'Create Or Update Resource Group'
        azureSubscription: 'YOURAZUREACCOUNT'
        resourceGroupName: '$(Build.BuildNumber)-$(APPNAME)-functionapp'
        location: 'australiaeast'
        csmFile: '$(Build.SourcesDirectory)/arm/$(templateName)/azuredeploy.json'
        csmParametersFile: '$(Build.SourcesDirectory)/arm/$(templateName)/azuredeploy.parameters.json'
        overrideParameters: '-appName "$(APPNAME)" -templateVersionId "$(Build.BuildId)" -accountId "$(ACCOUNTID)" -queryKey "$(QUERYKEY)" -endPoint "$(ENDPOINT)" -sessionKey "$(SESSIONKEY)" -sourceName "$(SOURCENAME)" -sourceCategory "$(SOURCECATEGORY)" -providerId "$(PROVIDERID)"'
      condition: or(eq(variables['fileChanged'], 'true'), variables['System.Debug'])

  - phase: build_artifacts
    dependsOn: foundation_deployment
    displayName: deploy source to Azure function
    queue:
      name: Hosted VS2017
      demands: npm
    steps:
    - task: NodeTool@0
      displayName: Use Node 6.x
    - task: Npm@1
      displayName: npm install
      inputs:
        workingDir: '.'
        verbose: false
    - task: ArchiveFiles@2
      displayName: Zip files
      inputs:
        rootFolderOrFile: .
        includeRootFolder: false
    - task: CopyPublishBuildArtifacts@1
      displayName: Copy Publish Artifact
      inputs:
        CopyRoot: '$(Build.ArtifactStagingDirectory)'
        Contents: '$(Build.BuildId).zip'
        ArtifactName: drop
        ArtifactType: Container
    - task: AzureRmWebAppDeployment@3
      displayName: Azure App Service Deploy
      inputs:
        azureSubscription: 'YOURAZUREACCOUNT'
        appType: functionapp
        WebAppName: '$(APPNAME)-$(Build.BuildId)'
        Package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
