phases:
  - phase: test_foundation_deployment
    displayName: test Azure function foundation
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    queue:
      name: Hosted VS2017
      demands: DotNetFramework
      matrix:
        functionapp:
          templateName: functionapp
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: Deploy resource group template
      inputs:
        action: 'Create Or Update Resource Group'
        azureSubscription: 'metricsstreamer'
        resourceGroupName: '$(Build.BuildNumber)-$(FUNCTIONAPPNAME)-functionapp'
        location: 'australiaeast'
        csmFile: '$(Build.SourcesDirectory)/arm/$(templateName)/azuredeploy.json'
        csmParametersFile: '$(Build.SourcesDirectory)/arm/$(templateName)/azuredeploy.parameters.json'
        overrideParameters: '-appName "$(FUNCTIONAPPNAME)" -environment "test" -templateVersionId "$(Build.BuildId)" -accountId "$(ACCOUNTID)" -queryKey "$(QUERYKEY)" -sessionKey "$(SESSIONKEY)" -providerId "$(PROVIDERID)"'
      condition: or(eq(variables['fileChanged'], 'true'), variables['System.Debug'])
    - task: AzureCLI@1
      displayName: Delete resource group - don't wait
      inputs:
        azureSubscription: 'metricsstreamer'
        scriptLocation: inlineScript
        inlineScript: az group delete --name $(Build.BuildNumber)-$(FUNCTIONAPPNAME)-functionapp --no-wait --yes

  - phase: publish_template_artifacts
    dependsOn: test_foundation_deployment
    displayName: build template artifacts
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    queue:
      name: Hosted VS2017
      matrix:
        functionapp:
          templateName: functionapp
    steps:
    - task: CopyFiles@2
      displayName: Publish template Artifact
      inputs:
        sourceFolder: $(Build.SourcesDirectory)
        contents: '**\arm\functionapp\**'
        targetFolder: $(Build.ArtifactStagingDirectory)\template
    - task: CopyPublishBuildArtifacts@1
      displayName: Copy Publish Artifact
      inputs:
        CopyRoot: '$(Build.ArtifactStagingDirectory)'
        Contents: '**\template\arm\functionapp\**'
        ArtifactName: 'templates'
        ArtifactType: Container

  - phase: build_test
    displayName: build test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    queue:
      name: Hosted VS2017
      demands: npm
    steps:
    - task: NodeTool@0
      displayName: Use Node 6.x
    - task: Npm@1
      displayName: npm install
      inputs:
        workingDir: '.'
        verbose: false
    - bash: npm install --global mocha
    - bash: mocha tests
      displayName: run mocha test

  - phase: publish_build_artifacts
    dependsOn: build_test
    displayName: build artifacts
    queue:
      name: Hosted VS2017
      demands: npm
    steps:
    - task: NodeTool@0
      displayName: Use Node 6.x
    - task: Npm@1
      displayName: npm install
      inputs:
        workingDir: '.'
        verbose: false
    - task: ArchiveFiles@2
      displayName: Zip files
      inputs:
        rootFolderOrFile: .
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/source.zip'
    - task: CopyPublishBuildArtifacts@1
      displayName: Copy Publish Artifact
      inputs:
        CopyRoot: '$(Build.ArtifactStagingDirectory)'
        Contents: 'source.zip'
        ArtifactName: 'release'
        ArtifactType: Container
